table dashboard_dataset
	lineageTag: fe304a65-c162-419b-bf2c-87cc32408369

	column id
		dataType: int64
		formatString: 0
		lineageTag: 9554c5a2-4e5e-495c-ae43-64a5b94a506d
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6865f9d8-071e-400b-8cf2-d6e334336be4
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column store_nbr
		dataType: int64
		formatString: 0
		lineageTag: bdd9879f-7ef4-498a-926b-cb6ee3af2a6d
		summarizeBy: none
		sourceColumn: store_nbr

		annotation SummarizationSetBy = Automatic

	column family
		dataType: string
		lineageTag: 66efa9c0-0b2b-464a-9bbe-a841465eba7a
		summarizeBy: none
		sourceColumn: family

		annotation SummarizationSetBy = Automatic

	column sales
		dataType: int64
		formatString: 0
		lineageTag: 0bbf487c-65cb-41d8-ba31-f5e1435a4a56
		summarizeBy: sum
		sourceColumn: sales

		annotation SummarizationSetBy = Automatic

	column onpromotion_x
		dataType: int64
		formatString: 0
		lineageTag: 5bfeac8c-c248-4f59-bd14-c29fd92d5dc4
		summarizeBy: sum
		sourceColumn: onpromotion_x

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: d787d6e6-3ab3-4e5b-8664-4a715e811761
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: 39766935-45e1-4dd1-8edc-474b224ae990
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column type_x
		dataType: string
		lineageTag: 9b0b851d-2909-4dfe-be9b-9ce352c7517d
		summarizeBy: none
		sourceColumn: type_x

		annotation SummarizationSetBy = Automatic

	column cluster
		dataType: int64
		formatString: 0
		lineageTag: 9dfdd5c2-22e3-4027-a21d-ed84e943ca0a
		summarizeBy: sum
		sourceColumn: cluster

		annotation SummarizationSetBy = Automatic

	column transactions_x
		dataType: int64
		formatString: 0
		lineageTag: 41f0dc25-9ef7-4145-964e-b18d8ab1a606
		summarizeBy: sum
		sourceColumn: transactions_x

		annotation SummarizationSetBy = Automatic

	column type_y
		dataType: string
		lineageTag: 644fd61a-50d5-4c8f-88d6-3cac862780de
		summarizeBy: none
		sourceColumn: type_y

		annotation SummarizationSetBy = Automatic

	column locale
		dataType: string
		lineageTag: 945246f2-cf32-48c1-9e57-541fb7cacbd5
		summarizeBy: none
		sourceColumn: locale

		annotation SummarizationSetBy = Automatic

	column locale_name
		dataType: string
		lineageTag: ca74f883-16bb-4c75-84b5-c87924ee325b
		summarizeBy: none
		sourceColumn: locale_name

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: 172d00da-ca8d-4691-9818-12045c66f4f0
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column transferred
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ea3d4327-51bf-467e-826f-c8ef315bfd63
		summarizeBy: none
		sourceColumn: transferred

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		formatString: 0
		lineageTag: 9e4ed840-9997-4cb0-bc99-a14a69e5f155
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: 294cd2c9-3852-4180-ad5f-74aa2425285d
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column day
		dataType: int64
		formatString: 0
		lineageTag: 6d9a44b5-a24e-447c-b26c-cf89186cc475
		summarizeBy: sum
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column day_of_week
		dataType: int64
		formatString: 0
		lineageTag: f022918d-1b52-402c-8055-ed873ba4f9eb
		summarizeBy: sum
		sourceColumn: day_of_week

		annotation SummarizationSetBy = Automatic

	column week_of_year
		dataType: int64
		formatString: 0
		lineageTag: d6809424-b9f9-4864-899e-bac09b7073f5
		summarizeBy: sum
		sourceColumn: week_of_year

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: 91574eb7-05ca-414e-9d8d-9cf0394431a6
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: int64
		formatString: 0
		lineageTag: 350a26f6-9e54-4434-800b-2e11fc8f6ab2
		summarizeBy: sum
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column lag_1
		dataType: int64
		formatString: 0
		lineageTag: e1229538-56da-4c12-a567-1730f40ea266
		summarizeBy: sum
		sourceColumn: lag_1

		annotation SummarizationSetBy = Automatic

	column lag_7
		dataType: int64
		formatString: 0
		lineageTag: d815e630-341f-4d18-becc-f506c1c4fb6d
		summarizeBy: sum
		sourceColumn: lag_7

		annotation SummarizationSetBy = Automatic

	column lag_14
		dataType: int64
		formatString: 0
		lineageTag: 40324ef0-1498-4f6d-9157-1ac06313d407
		summarizeBy: sum
		sourceColumn: lag_14

		annotation SummarizationSetBy = Automatic

	column lag_28
		dataType: int64
		formatString: 0
		lineageTag: 07813811-f4f2-4c1c-a952-d25c16fed68a
		summarizeBy: sum
		sourceColumn: lag_28

		annotation SummarizationSetBy = Automatic

	column rolling_mean_7
		dataType: double
		lineageTag: 5e5682a7-61d3-492f-ac96-c61f915d4358
		summarizeBy: sum
		sourceColumn: rolling_mean_7

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column rolling_std_7
		dataType: double
		lineageTag: ed457b10-9f6f-4a5c-858f-c7b34d105f0f
		summarizeBy: sum
		sourceColumn: rolling_std_7

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column rolling_mean_30
		dataType: double
		lineageTag: c6467e72-94a2-4abb-b333-93911f8f8409
		summarizeBy: sum
		sourceColumn: rolling_mean_30

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column promotion_flag
		dataType: int64
		formatString: 0
		lineageTag: d063ef26-036e-4388-862a-9acb6d74292c
		summarizeBy: sum
		sourceColumn: promotion_flag

		annotation SummarizationSetBy = Automatic

	column promotion_ratio
		dataType: int64
		formatString: 0
		lineageTag: bf66c25d-dcf7-466a-9115-d04eec8bc772
		summarizeBy: sum
		sourceColumn: promotion_ratio

		annotation SummarizationSetBy = Automatic

	column holiday_locale
		dataType: string
		lineageTag: 3a287f55-f81e-4d75-b368-e494a0c385a8
		summarizeBy: none
		sourceColumn: holiday_locale

		annotation SummarizationSetBy = Automatic

	column holiday_locale_name
		dataType: string
		lineageTag: d6bb7410-d310-47b7-abe9-ec038f6c91a6
		summarizeBy: none
		sourceColumn: holiday_locale_name

		annotation SummarizationSetBy = Automatic

	column holiday_description
		dataType: string
		lineageTag: ee0e6480-a390-4a92-915c-d65227d50ef9
		summarizeBy: none
		sourceColumn: holiday_description

		annotation SummarizationSetBy = Automatic

	column holiday_transferred
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e8fb89e1-533a-4d17-9f7e-8ac6fd9d2a26
		summarizeBy: none
		sourceColumn: holiday_transferred

		annotation SummarizationSetBy = Automatic

	column is_holiday
		dataType: int64
		formatString: 0
		lineageTag: 4788cc5d-12dd-4d48-aee4-6f221e05c1a4
		summarizeBy: sum
		sourceColumn: is_holiday

		annotation SummarizationSetBy = Automatic

	column holiday_type_Additional
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6edb20b1-2ed8-46ac-b00b-ef032c4069bd
		summarizeBy: none
		sourceColumn: holiday_type_Additional

		annotation SummarizationSetBy = Automatic

	column holiday_type_Bridge
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: eb5ec1d0-303c-4271-9dcd-ce30b01c3682
		summarizeBy: none
		sourceColumn: holiday_type_Bridge

		annotation SummarizationSetBy = Automatic

	column holiday_type_Event
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b41055c6-1d1c-4878-b7b0-28ed4d866f1d
		summarizeBy: none
		sourceColumn: holiday_type_Event

		annotation SummarizationSetBy = Automatic

	column holiday_type_Holiday
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 9e149011-4b48-4c68-91f7-fc360808d82c
		summarizeBy: none
		sourceColumn: holiday_type_Holiday

		annotation SummarizationSetBy = Automatic

	column holiday_type_Transfer
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 403e0dd2-3313-4b5e-a43a-19cca7c65811
		summarizeBy: none
		sourceColumn: holiday_type_Transfer

		annotation SummarizationSetBy = Automatic

	column 'holiday_type_Work Day'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 2548baf1-80f7-4459-9766-d59555b6711b
		summarizeBy: none
		sourceColumn: holiday_type_Work Day

		annotation SummarizationSetBy = Automatic

	column holiday_type_nan
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f81aea2f-85f9-48b8-9fb7-4b3a4726db1c
		summarizeBy: none
		sourceColumn: holiday_type_nan

		annotation SummarizationSetBy = Automatic

	column store_avg_sales
		dataType: double
		lineageTag: a8cd5b56-9477-43a3-8c36-02629a3cb781
		summarizeBy: sum
		sourceColumn: store_avg_sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column family_avg_sales
		dataType: double
		lineageTag: 5955aaeb-8b5a-4a45-9db9-4e0766cc6db5
		summarizeBy: sum
		sourceColumn: family_avg_sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column actual
		dataType: int64
		formatString: 0
		lineageTag: 25503a44-eae0-4c26-aab8-15153baa240f
		summarizeBy: sum
		sourceColumn: actual

		annotation SummarizationSetBy = Automatic

	column predicted
		dataType: double
		lineageTag: bebdcda1-8653-4733-a391-ede827c99c28
		summarizeBy: sum
		sourceColumn: predicted

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column residual
		dataType: double
		lineageTag: 1ae7e4f0-cc26-4282-a0d1-81068059448c
		summarizeBy: sum
		sourceColumn: residual

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column onpromotion_y
		dataType: int64
		formatString: 0
		lineageTag: 8ffbc42d-15eb-4724-9d99-b1d2cbfdffd6
		summarizeBy: sum
		sourceColumn: onpromotion_y

		annotation SummarizationSetBy = Automatic

	column transactions_y
		dataType: int64
		formatString: 0
		lineageTag: f433309e-728a-4c5b-963e-5ca2a582a6ca
		summarizeBy: sum
		sourceColumn: transactions_y

		annotation SummarizationSetBy = Automatic

	column 'Promotion Status' = ```
			
			IF(dashboard_dataset[onpromotion_x] > 0, "Promotion", "Non‑Promotion")
			
			```
		lineageTag: c42c6a58-d37d-4ad6-b250-37d259c639c2
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition dashboard_dataset = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\KC\retail-demand-forecasting\data\processed\dashboard_dataset.csv"),[Delimiter=",", Columns=51, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"id", Int64.Type}, {"date", type date}, {"store_nbr", Int64.Type}, {"family", type text}, {"sales", Int64.Type}, {"onpromotion_x", Int64.Type}, {"city", type text}, {"state", type text}, {"type_x", type text}, {"cluster", Int64.Type}, {"transactions_x", Int64.Type}, {"type_y", type text}, {"locale", type text}, {"locale_name", type text}, {"description", type text}, {"transferred", type logical}, {"year", Int64.Type}, {"month", Int64.Type}, {"day", Int64.Type}, {"day_of_week", Int64.Type}, {"week_of_year", Int64.Type}, {"quarter", Int64.Type}, {"is_weekend", Int64.Type}, {"lag_1", Int64.Type}, {"lag_7", Int64.Type}, {"lag_14", Int64.Type}, {"lag_28", Int64.Type}, {"rolling_mean_7", type number}, {"rolling_std_7", type number}, {"rolling_mean_30", type number}, {"promotion_flag", Int64.Type}, {"promotion_ratio", Int64.Type}, {"holiday_locale", type text}, {"holiday_locale_name", type text}, {"holiday_description", type text}, {"holiday_transferred", type logical}, {"is_holiday", Int64.Type}, {"holiday_type_Additional", type logical}, {"holiday_type_Bridge", type logical}, {"holiday_type_Event", type logical}, {"holiday_type_Holiday", type logical}, {"holiday_type_Transfer", type logical}, {"holiday_type_Work Day", type logical}, {"holiday_type_nan", type logical}, {"store_avg_sales", type number}, {"family_avg_sales", type number}, {"actual", Int64.Type}, {"predicted", type number}, {"residual", type number}, {"onpromotion_y", Int64.Type}, {"transactions_y", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

