------------------------
-- Measure: [MoM Growth]
------------------------
MEASURE _Measures[MoM Growth] = 
    DIVIDE(
        [Revenue This Month] - [Revenue Last Month],
        [Revenue Last Month]
    )
    , DisplayFolder = "_KPI"